### ISSUE TITLE
Error when creating a new recipient list

### ISSUE THREAD

**Issue by cremol** [michael-e/email_newsletter_manager#71]
I get the following error when creating a new recipient list:  
  
`Symphony Recoverable Error: Argument 2 passed to General::array_to_xml() must be of the type array, null given, called in /extensions/email_newsletter_manager/content/content.recipientgroups.php on line 87 and defined`  
  
Which is this line:  
`General::array_to_xml($field_elements, $field->fetchIncludableElements());`  
  
`$field->fetchIncludableElements()` are multiple arrays,  
if i print it i get:  
 `Array ( [0] => title ) Array ( [0] => images ) Array ( [0] => name ) Array ( [0] => email ) Array ( [0] => date )`  
  
It may have something to do with publish tab extension, see [here](http://www.getsymphony.com/discuss/thread/82064/10/#position-199).  
  
Uninstalling Publish tabs for me is not an option, so i hope you can help me out.  
  
I am using ENM 3.2.1 and symphony 2.6.4

**Comment by cremol** [comment]
Ok, after some more searching it does seem to be a Publish Tab issue, [this solved it for me](https://github.com/symphonists/publish_tabs/pull/28/commits/e1f160a1fb13efd79ee187ba728029f94ae2a476).

**Comment by michael-e** [comment]
Oh great! I am glad that you found it. So I will close this issue.
