### ISSUE TITLE
Warning: GenericErrorHandler 2: mysqli_connect(): (HY000/2002) using Mamp and localhost

### ISSUE THREAD

**Issue by wdebusschere** [michael-e/email_newsletter_manager#72]
Symphony 2.6.7 
ETM 7.3.1
ENM 3.3.0

When i try to send the newsletter with the symphony backend i get this error + status is sending, but nothing happens. 

`11/01/2017 6:27 pm > Warning: GenericErrorHandler 2: mysqli_connect(): (HY000/2002): No such file or directory on line 355 of file /Users/xxx/Sites/xxx/symphony/lib/toolkit/class.mysql.php
11/01/2017 6:27 pm > UNKNOWN: SymphonyErrorPage 0 - 2002: No such file or directory on line 655 of /Users/xxx/Sites/xxx/symphony/lib/core/class.symphony.php`

SMTP Gateway / sending mails only with ETM is working.
Also tried with sendmail, same error.

**Comment by michael-e** [comment]
The message is from the Symphony log, right? Is there anything in the ENM log (`manifest/newsletter-log.txt`)?

**Comment by wdebusschere** [comment]
Log from Symphony, no ENM log

**Comment by wdebusschere** [comment]
Frontend is also not working always get an error  <filter name="etm-tmp-notify-colaboradores2" status="failed">Can not send an email to nobody, please set a recipient.</filter>

**Comment by michael-e** [comment]
I don't really understand. What do you mean by "Frontend is also not working"? 

Have you set a recipient? If it's a dynamic recipient, can you instead use a single static recipient for testing?

**Comment by wdebusschere** [comment]
Frontend: event with the etm and enm.
If i set a static recipient in the etm it works, if i set a static receipient in the enm receipient group doesn't work. I'm uploading it to our server to try if it works there.

**Comment by michael-e** [comment]
Please try and tell me if it works. The error "Can not send an email to nobody" is hard to debug sometimes, but every time I had this it was my fault. :-)

If it doesn't work on the server, I can maybe tell you how to debug the situation by temporarily hacking some files.

**Comment by wdebusschere** [comment]
Exact same behaviour on the server.
Where can i find the recipients loop? :)
Thanks a lot

**Comment by michael-e** [comment]
Best way to debug this is to write to your own log file. I would start here:

https://github.com/michael-e/email_newsletter_manager/blob/3.3.0/lib/class.emailnewsletter.php#L202

Add this debugging code:

```php
file_put_contents('/Users/xxx/Sites/xxx/workspace/debug.txt', var_export($recipient, true), FILE_APPEND);
```

This should output the recipient array to `debug.txt`. It's inside the foreach loop, so it will do this for every recipient (unless it breaks).

**Comment by wdebusschere** [comment]
The code doesn't get to this line..

**Comment by michael-e** [comment]
I am pretty sure it does, because the *attempt to send* is a bit further down. Maybe your recipient is empty?

**Comment by michael-e** [comment]
Please try to output **all** (`$recipients`).

**Comment by wdebusschere** [comment]
The error is about the empty recipients, but this is configured correctly and in the Blueprints > Newsletter Recipients, shows 2 unique recipients.

**Comment by michael-e** [comment]
Yes, but maybe the recipients array has empty values, that is what I meant. Can you please output the complete array:

```php
file_put_contents('/Users/xxx/Sites/xxx/workspace/debug.txt', var_export($recipients, true), FILE_APPEND);
```

**Comment by wdebusschere** [comment]
no SHELL_EXEC on localhost nor Shared hosting. Maybe a good idea to test it in the extension.

**Comment by wdebusschere** [comment]
Warning: GenericErrorHandler 2: mysqli_connect(): (HY000/2002)
The reason is that "localhost" is a special name for the MySQL driver making it use the UNIX socket to connect to MySQL instead of the a TCP socket.

Solution: 

Mac OS X EL Capitan + MAMP Pro Do this

cd /var
sudo mkdir mysql
sudo chmod 755 mysql
cd mysql
sudo ln -s /Applications/MAMP/tmp/mysql/mysql.sock mysql.sock
Then do this

cd /tmp
sudo ln -s /Applications/MAMP/tmp/mysql/mysql.sock mysql.sock

**Comment by michael-e** [comment]
Version 3.7.0 adds a description of this issue as well as test code.
