### ISSUE TITLE
Configurable path to PHP executable

### ISSUE THREAD

**Issue by jurajkapsz** [michael-e/email_newsletter_manager#80]
In my webhosting environment I have to have defined a path to the [PHP executable](https://github.com/michael-e/email_newsletter_manager/blob/master/lib/class.emailbackgroundprocess.php#L7) like:

`shell_exec('env -i /some/path/to/php ...`

This breaks future updates with ENM upstream version.

It is only me? Or would it be useful to have a configurable path to the PHP executable, e.g. in `config.php`:

```php
###### EMAIL_NEWSLETTER_MANAGER ######
'enm' => array(
    'php_executable_path' => '',
),
########
```

Using latest ENM version 3.7.0

**Comment by michael-e** [comment]
This is a rare case. But still I consider your idea a valuable improvement.

I will have to find the time, however, to think about how to implement this properly. I will keep this issue open.

**Comment by jurajkapsz** [comment]
Thanks, that's fine with me.

**Comment by wdebusschere** [comment]
Very usefull, thanks!

**Comment by michael-e** [comment]
I hope you like it. :-) Feedback is welcome!

**Comment by jurajkapsz** [comment]
Absolutely perfect! Tested the latest v3.8.3 and everything works like a charm.

Thanks @michael-e !

**Comment by michael-e** [comment]
Thanks for the feedback!
