### ISSUE TITLE
Datasource ENM: group count doens't take in account the Email Newsletter Recipients filter

### ISSUE THREAD

**Issue by wdebusschere** [michael-e/email_newsletter_manager#81]
In the symphony backend the count of recipients is correct, but in the datasource i get 3 times group/@count=2..

Datasource:

```
<recipient-groups>
                    <group count="2">
                        <name id="group-custom-mailing">Group custom mailing</name>
                    </group>
</recipient-groups>
```

<img width="1431" alt="Screenshot 2019-06-10 at 16 43 13" src="https://user-images.githubusercontent.com/4136426/59207382-df5cb800-8b9e-11e9-9c3f-46d338a3d773.png">

**Comment by michael-e** [comment]
Honestly, with the given description I can not say anything. Please try and be more precise, and tell me how to reproduce the issue.

**Comment by wdebusschere** [comment]
My mistake, this is not an issue
